CREATE TABLE IF NOT EXISTS Guest (
    G_ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    F_name TEXT NOT NULL,
    L_name TEXT NOT NULL,
    Email TEXT UNIQUE,
    SSD TEXT,
    Age INTEGER
);

CREATE TABLE IF NOT EXISTS GuestPhones (
    PhoneID INTEGER PRIMARY KEY AUTOINCREMENT,
    Phone TEXT NOT NULL,
    G_ID INTEGER,
    FOREIGN KEY(G_ID) REFERENCES Guest(G_ID)
);

CREATE TABLE IF NOT EXISTS RoomType (
    RoomType_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Type_Name TEXT NOT NULL,
    PricePerNight REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS Room (
    R_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Number TEXT NOT NULL UNIQUE,
    Floor INTEGER NOT NULL,
    --Status ENUM ('Available', 'Booked', 'Under Maintenance') NOT NULL,
    Status TEXT NOT NULL,
    RoomType_ID INTEGER NOT NULL,
    FOREIGN KEY (RoomType_ID) REFERENCES RoomType(RoomType_ID)
);

CREATE TABLE IF NOT EXISTS Booking (
    B_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    G_ID INTEGER NOT NULL,
    R_ID INTEGER NOT NULL,
    Check_In_Date TEXT NOT NULL,
    Check_Out_Date TEXT NOT NULL,
    Booking_Date TEXT NOT NULL,
    Meal_Plan TEXT,
    --Status ENUM('Confirmed', 'Cancelled', 'Pending') NOT NULL,
    Status TEXT NOT NULL,
    FOREIGN KEY (G_ID) REFERENCES Guest(G_ID),
    FOREIGN KEY (R_ID) REFERENCES Room(R_ID)
);

CREATE TABLE IF NOT EXISTS Payment (
    Pay_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    B_ID INTEGER NOT NULL,
    Amount REAL NOT NULL,
    Payment_Date TEXT NOT NULL,
    --Payment_Method ENUM('Card', 'Cash', 'Online') NOT NULL,
    Payment_Method TEXT,
    FOREIGN KEY (B_ID) REFERENCES Booking(B_ID)
);

CREATE TABLE IF NOT EXISTS Staff (
    Staff_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    F_name TEXT NOT NULL,
    L_name TEXT NOT NULL,
    Role TEXT NOT NULL,
    Phone TEXT NOT NULL,
    Email TEXT NOT NULL UNIQUE,
    Salary REAL NOT NULL,
    HireDate TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Shift (
    Shift_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Staff_ID INTEGER NOT NULL,
    ShiftName TEXT NOT NULL,
    StartTime TEXT NOT NULL,
    EndTime TEXT NOT NULL,
    FOREIGN KEY(Staff_ID) REFERENCES Staff(Staff_ID)
);
