CREATE TABLE IF NOT EXISTS Guest (
    G_ID INT AUTOINCREMENT PRIMARY KEY, 
    F_name VARCHAR(20) NOT NULL,
    L_name VARCHAR(20) NOT NULL,
    Email VARCHAR(50) UNIQUE,
    SSD VARCHAR(20),
    Age INT
);
SELECT * FROM Guest;

CREATE TABLE IF NOT EXISTS GuestPhones (
    PhoneID INT AUTOINCREMENT PRIMARY KEY,
    Phone VARCHAR(20) NOT NULL,
    G_ID INT,
    FOREIGN KEY(G_ID) REFERENCES Guest(G_ID)
);
SELECT * FROM GuestPhones;

CREATE TABLE IF NOT EXISTS RoomType (
    RoomType_ID INT AUTOINCREMENT PRIMARY KEY,
    Type_Name VARCHAR(20) NOT NULL,
    PricePerNight DECIMAL(10,2) NOT NULL
);
SELECT * FROM RoomType;

CREATE TABLE IF NOT EXISTS Room (
    R_ID INT AUTOINCREMENT PRIMARY KEY,
    Number VARCHAR(10) NOT NULL UNIQUE,
    Floor INT NOT NULL,
    --Status ENUM ('Available', 'Booked', 'Under Maintenance') NOT NULL,
    Status VARCHAR(20) NOT NULL,
    RoomType_ID INT NOT NULL,
    FOREIGN KEY (RoomType_ID) REFERENCES RoomType(RoomType_ID)
);
SELECT * FROM Room;

CREATE TABLE IF NOT EXISTS Booking (
    B_ID INT AUTOINCREMENT PRIMARY KEY,
    G_ID INT NOT NULL,
    R_ID INT NOT NULL,
    Check_In_Date DATE NOT NULL,
    Check_Out_Date DATE NOT NULL,
    Booking_Date DATE NOT NULL,
    Meal_Plan VARCHAR(50),
    --Status ENUM('Confirmed', 'Cancelled', 'Pending') NOT NULL,
    Status VARCHAR(20) NOT NULL,
    FOREIGN KEY (G_ID) REFERENCES Guest(G_ID),
    FOREIGN KEY (R_ID) REFERENCES Room(R_ID)
);
SELECT * FROM booking;

CREATE TABLE IF NOT EXISTS Payment (
    Pay_ID INT AUTOINCREMENT PRIMARY KEY,
    B_ID INT NOT NULL,
    Amount DECIMAL(10,2) NOT NULL,
    Payment_Date DATE NOT NULL,
    --Payment_Method ENUM('Card', 'Cash', 'Online') NOT NULL,
    Payment_Method VARCHAR(10),
    FOREIGN KEY (B_ID) REFERENCES Booking(B_ID)
);
SELECT * FROM payment;

CREATE TABLE IF NOT EXISTS Staff (
    Staff_ID INT AUTOINCREMENT PRIMARY KEY,
    F_name VARCHAR(20) NOT NULL,
    L_name VARCHAR(20) NOT NULL,
    Role VARCHAR(40) NOT NULL,
    Phone VARCHAR(20) NOT NULL,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Salary DECIMAL(10,2) NOT NULL,
    HireDate DATE NOT NULL
);
SELECT * FROM staff;

CREATE TABLE IF NOT EXISTS Shift (
    Shift_ID INT AUTOINCREMENT PRIMARY KEY,
    Staff_ID INT NOT NULL,
    ShiftName VARCHAR(50) NOT NULL,
    StartTime TIME NOT NULL,
    EndTime TIME NOT NULL,
    FOREIGN KEY(Staff_ID) REFERENCES Staff(Staff_ID)
);
SELECT * FROM shift;
